services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend-stable:
    image: ghcr.io/amritray01/policyforge/backend:stable
    environment:
      DATABASE_URL: postgresql://postgres:${DB_PASSWORD}@db:5432/policyforge
    depends_on:
      - db

  app-stable:
    image: ghcr.io/amritray01/policyforge/frontend:stable

  app-canary:
    image: ghcr.io/amritray01/policyforge/frontend:canary

  nginx-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app-stable
      - app-canary
      - backend-stable

volumes:
  postgres_data: