events {}

http {
  upstream App-Stable {
    server App-Stable:80;
  }

  upstream App-Canary {
    server App-Canary:80;
  }

  upstream Backend-Stable {
    server Backend-Stable:5000;
  }

  upstream Backend-Canary {
    server Backend-Canary:5000;
  }

  # Canary split (80% v1, 20% v2)
  split_clients "${remote_addr}" $frontend_upstream {
    80% App-Stable;
    20% App-Canary;
  }

  split_clients "${remote_addr}" $backend_upstream {
    80% Backend-Stable;
    20% Backend-Canary;
  }

  server {
    listen 80;

    location / {
      proxy_pass http://$frontend_upstream;
    }

    location /api/ {
      proxy_pass http://$backend_upstream;
    }
  }
}