events {}

http {
  upstream frontend_v1 {
    server frontend_v1:80;
  }

  upstream frontend_v2 {
    server frontend_v2:80;
  }

  upstream backend_v1 {
    server backend_v1:3000;
  }

  upstream backend_v2 {
    server backend_v2:3000;
  }

  # Canary split (80% v1, 20% v2)
  split_clients "${remote_addr}" $frontend_upstream {
    80% frontend_v1;
    20% frontend_v2;
  }

  split_clients "${remote_addr}" $backend_upstream {
    80% backend_v1;
    20% backend_v2;
  }

  server {
    listen 80;

    location / {
      proxy_pass http://$frontend_upstream;
    }

    location /api/ {
      proxy_pass http://$backend_upstream;
    }
  }
}