upstream stable_frontend {
    server App-Stable:80;
}

upstream canary_frontend {
    server App-Canary:80;
}

upstream backend_stable {
    # Assuming your Express backend is listening on port 5000 inside its container
    server Backend-Stable:5000; 
}

server {
    listen 80;

    # 1. Backend API Routing
    location /api/ {
        # This passes the /api/ prefix directly to Express.
        proxy_pass http://backend_stable;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 2. Canary Frontend Routing
    location /v2/ {
        # It strips the '/v2/' prefix so the Canary container just sees a normal request for its root files.
        proxy_pass http://canary_frontend/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 3. Stable Frontend Routing (Default)
    location / {
        proxy_pass http://stable_frontend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}